/*****************************************图标***************************************/

//login
#define IMAGE_PSW_CLEAR @"ic_删除"
#define IMAGE_PSW_HIDDEN @"ic_隐藏密码"
#define IMAGE_PSW_VISIBLE @"ic_密码可见"
#define IMAGE_AGREE_NORMAL @"ic_同一用户协议_normal"
#define IMAGE_AGREE_PRESSED @"ic_同意用户协议_pressed"
#define IMAGE_CLOSE @"ic_关闭"

//main
#define IMAGE_HOME_NORMAL @"ic_首页"
#define IMAGE_HOME_PRESSED @"ic_首页_选中"
#define IMAGE_CAPITAL_NORMAL @"ic_资金"
#define IMAGE_CAPITAL_PRESSED  @"ic_资金_选中"
#define IMAGE_MSG_NORMAL @"ic_消息"
#define IMAGE_MSG_PRESSED @"ic_消息_选中"
#define IMAGE_MINE_NORMAL @"ic_我的"
#define IMAGE_MINE_PRESSED @"ic_我的_选中"
#define IMAGE_SHELVES @"ic_货架"
#define IMAGE_SHELVES_PRESSED @"ic_货架_选中"

#define IMAGE_SHOP @"ic_选品站"
#define IMAGE_SHOP_PRESSED @"ic_选品站_选中"

//home
#define IMAGE_HOME_BG @"ic_首页背景"
#define IMAGE_SEARCH @"ic_搜索"
#define IMAGE_PRODUCT_BACK @"ic_产品详情_返回"
#define IMAGE_PRODUCT_ADD @"ic_产品详情_加入选品站"
#define IMAGE_PRODUCT_MSG @"ic_产品详情_消息"

//captial
#define IMAGE_CAPITAL_TITLE @"ic_资金_标题"
#define IMAGE_CAPITAL_BG @"ic_资金_背景"
#define IMAGE_CAPITAL_MCH_BG @"ic_资金_供应商"
#define IMAGE_WITHDRAW_BANK @"ic_提现_银行卡"
#define IMAGE_WITHDRAW_ALIPAY @"ic_提现_支付宝"

//mine
#define IMAGE_MINE_CONFIRM @"ic_个人中心_待确认"
#define IMAGE_MINE_RECEIVE @"ic_个人中心_待收货"
#define IMAGE_MINE_BUSINESS @"ic_个人中心_个人名片"
#define IMAGE_MINE_ALL @"ic_个人中心_全部"
#define IMAGE_MINE_QUALIFICATIONS @"ic_个人中心_认证资质"
#define IMAGE_MINE_SETTING @"ic_个人中心_设置"
#define IMAGE_MINE_ADDRESS @"ic_个人中心_收货地址"
#define IMAGE_MINE_CAPITAL_ACCOUNT @"ic_个人中心_收款账户"
#define IMAGE_MINE_CELEBRITY_MANAGE @"ic_个人中心_主播管理"
#define IMAGE_MINE_MCN @"ic_个人中心_所属机构"
#define IMAGE_MINE_PARTNER @"ic_个人中心_已合作"
#define IMAGE_MINE_CANCEL @"ic_个人中心_已取消"
#define IMAGE_MINE_AUTH @"ic_个人中心_已认证"
#define IMAGE_MINE_NOT_AUTH @"ic_个人中心_未认证"
#define IMAGE_QULIFICATIONS_CELEBRITY @"ic_资质认证_主播"
#define IMAGE_QULIFICATIONS_MERCHANT @"ic_资质认证_商户"
#define IMAGE_QULIFICATIONS_MCN @"ic_资质认证_MCN"
#define IMAGE_IDETIFY_FRONT @"ic_身份证_正面示意"
#define IMAGE_IDETIFY_BACK @"ic_身份证_反面示意"
#define IMAGE_IDETIFY_ADD @"ic_添加照片"
#define IMAGE_ADDRESSINFO_BOTTOM @"ic_地址装饰"
#define IMAGE_GENDER_MALE @"ic_男"
#define IMAGE_GENDER_FEMALE @"ic_女"
#define IMAGE_BUSINESS_BG @"ic_个人名片"
#define IMAGE_BANK_PERSONAL @"ic_个人银行卡"
#define IMAGE_BANK_PUBLIC @"ic_对公银行卡"
#define IMAGE_BANK_ALIPAY @"ic_支付宝"
#define IMAGE_CHANGE_ACCOUNT_ADD @"ic_添加新账号"
#define IMAGE_MINE_MALE @"ic_个人名片_男"
#define IMAGE_MINE_FEMALE @"ic_个人名片_女"

//shop
#define IMAGE_EXPAND @"ic_展开"
#define IMAGE_NARROW @"ic_收起"
#define IMAGE_SELECT @"ic_选中"
#define IMAGE_NO_SELECT @"ic_未选中"
#define IMAGE_NO_SELECT2 @"ic_未选中2"
#define IMAGE_SHOP_BG @"ic_选品站_背景"
#define IMAGE_ARROW_RIGHT_GREY @"ic_跳转_浅灰"
#define IMAGE_ADDRESS_MASK @"ic_地址_蒙版"

//partner
#define IMAGE_PARTNER_MCN @"ic_MCN机构"
#define IMAGE_PARTNER_CELEBRITY @"ic_主播信息"
#define IMAGE_PARTNER_MERCHANT @"ic_商家信息"
#define IMAGE_PARTNER_SCHEDULE @"ic_合作进度"
#define IMAGE_PARTNER_LOGISTICAL @"ic_物流信息"
#define IMAGE_LAYER_CLOSE @"ic_关闭_上滑弹层"


//未添加图片
#define IMAGE_LIGHT_BACK @"ic_返回_浅色"
#define IMAGE_DARK_BACK @"ic_返回_深色"
#define IMAGE_SCAN_LINE @"ic_扫描线"
#define IMAGE_SCAN @"ic_扫码"
#define IMAGE_VERSION_UPDATE @"ic_版本更新"
#define IMAGE_TIPS @"ic_提示"
#define IMAGE_SUCCESS @"ic_成功"
#define IMAGE_BANK_LAYER @"ic_上传遮罩"
#define IMAGE_REFRESH @"ic_下拉"
#define IMAGE_LIGHT_NEXT @"ic_跳转_浅色"
#define IMAGE_DARK_NEXT @"ic_跳转_深色"
#define IMAGE_NO_DATA @"ic_无数据"
#define IMAGE_ERROR @"ic_error"
#define IMAGE_ICON @"icon"
#define IMAGE_DEFAULT @"ic_默认头像"
